Atualizando step

diff --git a/.github/workflows/check-boundaries-template.yml b/.github/workflows/check-boundaries-template.yml
--- a/.github/workflows/check-boundaries-template.yml
+++ b/.github/workflows/check-boundaries-template.yml
@@ -25,7 +25,8 @@ jobs:
             echo "- $file"
           done
       
-      - name: Listing files outside ${{ inputs.boundary_folder }}
+      - name: Listing files outside ${{ inputs.boundary_folder }} directory
+        id: outside-boundary-files
         env:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
           BOUNDARY_FOLDER: ${{ inputs.boundary_folder }}
@@ -39,3 +40,15 @@ jobs:
               echo "- $file"
             fi
           done
+
+          echo "outside-boundary-changed-files=$files_outside_boundary" >> $OUTSIDE_BOUNDARY_CHANGED_FILES
+
+      - name: Checking files outside ${{ inputs.boundary_folder }} directory
+        env:
+          OUTSIDE_BOUNDARY_CHANGED_FILES: ${{ steps.outside-boundary-files.outputs.outside-boundary-changed-files }}
+          BOUNDARY_FOLDER: ${{ inputs.boundary_folder }}
+        run: |
+          if [ ${#$OUTSIDE_BOUNDARY_CHANGED_FILES} -gt 0 ]; then
+              echo "Error: There are changed files outside $BOUNDARY_FOLDER"
+              exit 1
+          fi
